### ISSUE TITLE
Error "The Procedure entry point vkResetQueryPool could not be located in the dynamic link library C:\Users\USERNAME\Downloads\IOLITE\Iolite,exe"

### ISSUE THREAD

**Issue by Saarlooswolf** [MissingDeadlines/iolite#46]
I just installed iolite on windows 10 22h2 and it doesn't launch. I just get the error "The Procedure entry point vkResetQueryPool could not be located in the dynamic link library C:\Users\USERNAME\Downloads\IOLITE\Iolite.exe". 

**System Specs:**
CPU: intel core i5-8300H running at 2.30GHz
RAM: 8GB
GPU: Intel UHD Graphics 630

I have Vulkan working on my device and the latest graphics drivers that Dell recommends. Does anyone know how to fix the error Does anyone know how to fix this?

![Screenshot 2024-02-23 134049](https://github.com/MissingDeadlines/iolite/assets/146884740/3e703f51-7066-4d96-9575-96841f816370)

**Comment by begla** [comment]
A fundamental Vulkan API function is missing. Your GPU should support the Vulkan API up to version 1.3, which is fine since IOLITE only requires API version 1.2.

Updating your GPU driver should fix the issue. To be safe, please also update your CPU chipset drivers while at it. Feel free to reopen if this does not resolve the issue.
